In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import numpy as np
import os

In [ ]:
filename = "discharge_klu.csv"
file_path = '/content/drive/My Drive/RS - IEEE - ESA/notebooks/notebooks - sesión 2/discharge_klu.csv'  # ajusta la ruta
df = pd.read_csv(file_path, index_col='Phenomenon', parse_dates=True, skiprows=3)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 7: invalid continuation byte

In [ ]:
df.index = pd.to_datetime(df.index, utc=True)
df_resampled = df.resample('1h').mean()
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1375033 entries, 2009-12-31 23:00:00+00:00 to 2025-12-31 22:59:30+00:00
Data columns (total 1 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Abfluss (m³/s)  1375033 non-null  float64
dtypes: float64(1)
memory usage: 21.0 MB

In [ ]:
df_resampled.tail()

                           Abfluss (m³/s)
Phenomenon
2025-12-31 18:00:00+00:00        3.654000
2025-12-31 19:00:00+00:00        3.644000
2025-12-31 20:00:00+00:00        3.698000
2025-12-31 21:00:00+00:00        3.664444
2025-12-31 22:00:00+00:00        3.655000

In [ ]:
df_resampled.head(10)

                           Abfluss (m³/s)
Phenomenon
2009-12-31 23:00:00+00:00       30.734000
2010-01-01 00:00:00+00:00       30.506667
2010-01-01 01:00:00+00:00       30.367500
2010-01-01 02:00:00+00:00       30.233333
2010-01-01 03:00:00+00:00       30.076667
2010-01-01 04:00:00+00:00       29.896667
2010-01-01 05:00:00+00:00       29.800000
2010-01-01 06:00:00+00:00       29.650000
2010-01-01 07:00:00+00:00       29.500000
2010-01-01 08:00:00+00:00       29.392500

In [ ]:
df.tail()

                           Abfluss (m³/s)
Phenomenon
2025-12-31 23:35:00+01:00            3.60
2025-12-31 23:40:00+01:00            3.63
2025-12-31 23:55:00+01:00            3.63
2025-12-31 23:55:05+01:00            3.78
2025-12-31 23:59:30+01:00            3.82

In [ ]:
df_resampled = df.resample('15min').mean()
df_resampled.head()

TypeError: agg function failed [how->mean,dtype->object]